### ISSUE TITLE
SipTrace with MySQL

### ISSUE THREAD

**Issue by hogbinj** [OpenSIPS/opensips-cp#83]
The standard empty query returns no results.

Looking at the database
SELECT DISTINCT callid FROM sip_trace WHERE status='' AND direction='in' ORDER BY id DESC;

gets

ERROR 3065 (HY000): Expression #1 of ORDER BY clause is not in SELECT list, references column 'opensips.sip_trace.id' which is not in SELECT list; this is incompatible with DISTINCT

I fixed it in opensips/web/tools/system/siptrace/template/tracer.main.php

where line 140 needed to change id to callid to match the postgres call below it,

**Comment by liviuchircu** [comment]
@hogbinj can you please do:

`mysql> show global variables like '%sql_mode%';`

and post the output?  I suspect you are using the `ONLY_FULL_GROUP_BY` mode, which does not allow such queries.

The `id` -> `callid` fix is not correct, because it changes the behavior of the tool:  instead of displaying calls in "latest calls first" fashion, it will randomly display them in "reverse-alphabetical order of Call-ID"...

**Comment by liviuchircu** [comment]
@hogbinj I managed to find a fix that will work with any SQL mode.  Cheers!
